# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scores', models.BigIntegerField(default=0)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
