# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='scores',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
